baseURL = 'https://blog-bpy.pages.dev'
languageCode = 'it-IT'
title = 'Nicolò Frescura'
theme = 'PaperMod'
enableRobotsTXT = true

[params]
ShowShareButtons = true
ShowReadingTime = true
ShowToc = true
TocOpen = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true

[params.homeInfoParams]
Title = "Benvenuto 👋"
Content = ""

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/NikoFresh"

[[params.socialIcons]]
name = "Instagram"
url = "https://instagram.com/NikoFresh"

[[menu.main]]
identifier = "search"
name = "Cerca"
url = "/search/"
weight = 10

[outputs]
home = [ "HTML", "RSS", "JSON" ]